export const standardizedPricingRules = [
  {
    name: 'Standard distance fallback',
    minDistance: 0,
    maxDistance: 9999,
    baseFare: 85,
    pricePerKm: 1.50,
    operationsRatePerKm: 0.75,
    discount: 0,
    sortOrder: 1
  }
]

export const standardizedPricingZones = [
  { code: 'SJO-METRO', name: 'San Jose metro', oneWayPrice: 85, notes: 'SJO airport to central San Jose hotels.', sortOrder: 1 },
  { code: 'SJO-VARA-BLANCA', name: 'Poas and Vara Blanca', oneWayPrice: 135, notes: 'Poas Volcano and Vara Blanca lodging.', sortOrder: 2 },
  { code: 'SJO-JACO', name: 'Jaco', oneWayPrice: 200, notes: 'Jaco and nearby central Pacific lodging.', sortOrder: 3 },
  { code: 'SJO-MOUNTAIN-250', name: 'Dota and Caribbean highlands', oneWayPrice: 250, notes: 'San Gerardo de Dota, Guacimo highlands, and comparable access routes.', sortOrder: 4 },
  { code: 'SJO-MOUNTAIN-265', name: 'Monteverde and Manuel Antonio', oneWayPrice: 265, notes: 'Commercial tier for Monteverde and Manuel Antonio lodging.', sortOrder: 5 },
  { code: 'SJO-ARENAL', name: 'La Fortuna and Arenal', oneWayPrice: 265, notes: 'La Fortuna and standard Arenal lodging. Remote properties may use a fixed override.', sortOrder: 6 },
  { code: 'SJO-PEREZ-ZELEDON', name: 'Perez Zeledon', oneWayPrice: 300, notes: 'Perez Zeledon and nearby mountain lodging.', sortOrder: 7 },
  { code: 'SJO-UVITA', name: 'Uvita and Bahia Ballena', oneWayPrice: 350, notes: 'Uvita, Bahia Ballena, and nearby lodging.', sortOrder: 8 },
  { code: 'SJO-PAPAGAYO', name: 'Papagayo resorts', oneWayPrice: 365, notes: 'Papagayo resort area.', sortOrder: 9 },
  { code: 'SJO-SIERPE', name: 'Sierpe', oneWayPrice: 425, notes: 'Sierpe transfer hub. Boat schedules should be confirmed.', requiresReview: true, sortOrder: 10 },
  { code: 'SJO-LONG-COAST', name: 'Long coastal routes', oneWayPrice: 450, notes: 'Guanacaste beaches, south Caribbean, Samara, and Tambor standard access.', sortOrder: 11 },
  { code: 'SJO-REMOTE-NICOYA', name: 'Remote Nicoya', oneWayPrice: 550, notes: 'Remote Nicoya Peninsula routes with longer access time.', requiresReview: true, sortOrder: 12 },
  { code: 'SJO-BORDER-REMOTE', name: 'Border and far remote routes', oneWayPrice: 700, notes: 'Border crossings and far remote destinations require operational confirmation.', requiresReview: true, sortOrder: 13 }
]

export const standardizedPlaces = [
  { name: 'SJO Airport', zone: 'Alajuela', description: 'Private airport pickups and drop-offs with flight-aware scheduling.', featured: true },
  { name: 'Hotel Presidente', zone: 'San Jose', pricingZoneCode: 'SJO-METRO' },
  { name: 'Peace Lodge Vara Blanca', zone: 'Vara Blanca', pricingZoneCode: 'SJO-VARA-BLANCA', description: 'A mountain transfer near Poas Volcano, waterfalls, and cloud forest scenery.' },
  { name: 'Jaco Beach', zone: 'Central Pacific', pricingZoneCode: 'SJO-JACO', featured: true, updateDescription: true, description: 'A lively Pacific beach town known for surf, restaurants, and easy coastal connections.' },
  { name: 'Best Western Jaco', zone: 'Central Pacific', pricingZoneCode: 'SJO-JACO' },
  { name: 'Manuel Antonio', zone: 'Central Pacific', pricingZoneCode: 'SJO-MOUNTAIN-265', featured: true, updateDescription: true, description: 'Rainforest, beaches, wildlife, and private hotel transfers around Quepos and Manuel Antonio.' },
  { name: 'Hotel Parador', zone: 'Manuel Antonio', pricingZoneCode: 'SJO-MOUNTAIN-265' },
  { name: 'Monteverde', zone: 'Cloud Forest', pricingZoneCode: 'SJO-MOUNTAIN-265', featured: true, updateDescription: true, description: 'Cloud forest reserves, mountain lodges, and adventure experiences above the treetops.' },
  { name: 'Hotel El Establo', zone: 'Monteverde', pricingZoneCode: 'SJO-MOUNTAIN-265' },
  { name: 'Hotel Poco a Poco', zone: 'Monteverde', pricingZoneCode: 'SJO-MOUNTAIN-265' },
  { name: 'La Fortuna / Arenal', zone: 'Northern Highlands', pricingZoneCode: 'SJO-ARENAL', featured: true, updateDescription: true, description: 'Volcano views, hot springs, adventure parks, and rainforest lodges around La Fortuna.' },
  { name: 'Hotel The Springs', zone: 'Arenal', pricingZoneCode: 'SJO-ARENAL' },
  { name: 'Arenal Observatory Lodge', zone: 'Arenal', pricingZoneCode: 'SJO-ARENAL' },
  { name: 'San Gerardo de Dota', zone: 'Los Santos', pricingZoneCode: 'SJO-MOUNTAIN-250', description: 'Cool mountain air, quetzal habitat, forest trails, and quiet highland lodges.' },
  { name: 'Dantica Lodge', zone: 'San Gerardo de Dota', pricingZoneCode: 'SJO-MOUNTAIN-250' },
  { name: 'Trogon Lodge', zone: 'San Gerardo de Dota', pricingZoneCode: 'SJO-MOUNTAIN-250' },
  { name: 'Hotel ECOLIRIOS', zone: 'Guacimo', pricingZoneCode: 'SJO-MOUNTAIN-250' },
  { name: 'Hostel El Lugar', zone: 'Costa Rica', pricingZoneCode: 'SJO-MOUNTAIN-250' },
  { name: 'Alta Gracia', zone: 'Perez Zeledon', pricingZoneCode: 'SJO-PEREZ-ZELEDON' },
  { name: 'Uvita / Bahia Ballena', zone: 'South Pacific', pricingZoneCode: 'SJO-UVITA', description: 'A relaxed South Pacific base for whale watching, waterfalls, beaches, and rainforest.' },
  { name: 'Bodhi Surf and Yoga', zone: 'Bahia Ballena', pricingZoneCode: 'SJO-UVITA' },
  { name: 'Sierpe', zone: 'Osa', pricingZoneCode: 'SJO-SIERPE' },
  { name: 'Puerto Viejo', zone: 'South Caribbean', pricingZoneCode: 'SJO-LONG-COAST', description: 'Caribbean beaches, local cuisine, wildlife, and a distinctive Afro-Caribbean culture.' },
  { name: 'Hotel Le Cameleon', zone: 'Puerto Viejo', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Tamarindo', zone: 'Guanacaste', pricingZoneCode: 'SJO-LONG-COAST', featured: true, updateDescription: true, description: 'A popular Guanacaste beach destination for surfing, sunsets, dining, and coastal stays.' },
  { name: 'Playa Conchal', zone: 'Guanacaste', pricingZoneCode: 'SJO-LONG-COAST', description: 'Clear water, pale shell sand, and resort stays on Costa Rica north Pacific coast.' },
  { name: 'Marina Flamingo', zone: 'Guanacaste', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Hotel Westin', zone: 'Guanacaste', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Hotel Capitan Suizo', zone: 'Tamarindo', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Hotel Blue Iguana Samara', zone: 'Samara', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Playa Tambor', zone: 'Nicoya Peninsula', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Riu Palace', zone: 'Papagayo', pricingZoneCode: 'SJO-PAPAGAYO' },
  { name: 'Four Seasons', zone: 'Papagayo', pricingZoneCode: 'SJO-PAPAGAYO' },
  { name: 'Lagarta Lodge', zone: 'Nosara', pricingZoneCode: 'SJO-REMOTE-NICOYA' },
  { name: 'Hotel Punta Islita', zone: 'Nicoya Peninsula', pricingZoneCode: 'SJO-REMOTE-NICOYA' },
  { name: 'Playa El Jobo', zone: 'La Cruz', pricingZoneCode: 'SJO-REMOTE-NICOYA' },
  { name: 'Villa Habana Mal Pais', zone: 'Nicoya Peninsula', pricingZoneCode: 'SJO-LONG-COAST' },
  { name: 'Hotel Botanika', zone: 'Osa Peninsula', pricingZoneCode: 'SJO-BORDER-REMOTE' },
  { name: 'Paso Canoas', zone: 'South Border', pricingZoneCode: 'SJO-BORDER-REMOTE' },
  { name: 'Coto Brus', zone: 'South Pacific Highlands', pricingZoneCode: 'SJO-BORDER-REMOTE' },
  { name: 'Penas Blancas Northern Border', zone: 'North Border', pricingZoneCode: 'SJO-BORDER-REMOTE' },
  { name: 'Sixaola Border', zone: 'South Caribbean Border', pricingZoneCode: 'SJO-BORDER-REMOTE' }
]

export const fixedPriceExceptions = [
  { destinationName: 'Hotel The Springs', price: 255, label: 'The Springs', notes: 'Workbook exception below the standard Arenal zone.' },
  { destinationName: 'Arenal Observatory Lodge', price: 285, label: 'Arenal Observatory', notes: 'Remote Arenal access override.' },
  { destinationName: 'Playa El Jobo', price: 575, label: 'El Jobo', notes: 'Far north coastal access override.' },
  { destinationName: 'Villa Habana Mal Pais', price: 600, label: 'Mal Pais via ferry', notes: 'Ferry timing and peninsula access require confirmation.' }
]

export const sourceTariffs = [
  { destinationName: 'Hotel Presidente', expectedPrice: 85 },
  { destinationName: 'Best Western Jaco', expectedPrice: 200 },
  { destinationName: 'Hotel Parador', expectedPrice: 265 },
  { destinationName: 'Bodhi Surf and Yoga', expectedPrice: 350 },
  { destinationName: 'Sierpe', expectedPrice: 425 },
  { destinationName: 'Hotel Botanika', expectedPrice: 700 },
  { destinationName: 'Paso Canoas', expectedPrice: 700 },
  { destinationName: 'Coto Brus', expectedPrice: 700 },
  { destinationName: 'Hotel The Springs', expectedPrice: 255 },
  { destinationName: 'Arenal Observatory Lodge', expectedPrice: 285 },
  { destinationName: 'Marina Flamingo', expectedPrice: 450 },
  { destinationName: 'Hotel Westin', expectedPrice: 450 },
  { destinationName: 'Hotel Capitan Suizo', expectedPrice: 450 },
  { destinationName: 'Lagarta Lodge', expectedPrice: 550 },
  { destinationName: 'Hotel Punta Islita', expectedPrice: 550 },
  { destinationName: 'Hotel Blue Iguana Samara', expectedPrice: 450 },
  { destinationName: 'Riu Palace', expectedPrice: 365 },
  { destinationName: 'Four Seasons', expectedPrice: 365 },
  { destinationName: 'Playa El Jobo', expectedPrice: 575 },
  { destinationName: 'Peace Lodge Vara Blanca', expectedPrice: 135 },
  { destinationName: 'Penas Blancas Northern Border', expectedPrice: 700 },
  { destinationName: 'Hotel El Establo', expectedPrice: 265 },
  { destinationName: 'Hotel Poco a Poco', expectedPrice: 265 },
  { destinationName: 'Hotel Le Cameleon', expectedPrice: 450 },
  { destinationName: 'Sixaola Border', expectedPrice: 700 },
  { destinationName: 'Hostel El Lugar', expectedPrice: 250 },
  { destinationName: 'Hotel ECOLIRIOS', expectedPrice: 250 },
  { destinationName: 'Dantica Lodge', expectedPrice: 250 },
  { destinationName: 'Trogon Lodge', expectedPrice: 250 },
  { destinationName: 'Alta Gracia', expectedPrice: 300 },
  { destinationName: 'Playa Tambor', expectedPrice: 450 },
  { destinationName: 'Villa Habana Mal Pais', expectedPrice: 600 }
]
